import express, { json, urlencoded } from "express";
import { RegisterRoutes } from "./routes/routes.ts";
import "./routes/reefapi.v0.ts";

const app = express();
// Middleware to parse JSON and URL-encoded data
app.use(urlencoded({ extended: true }));
app.use(json());

// Register routes generated by TSOA
RegisterRoutes(app);
