import express, { json, urlencoded } from 'express';
import cors from 'cors';
import { RegisterRoutes } from './routes/routes';
import './routes/reefapi.v0';

const app = express();

// Middleware to parse JSON and URL-encoded data
app.use(urlencoded({ extended: true }));
app.use(json());

// Enable CORS
app.use(cors());

// Register routes generated by TSOA
RegisterRoutes(app);

// Handle 404 errors
app.use((req, res) => {
  res.status(404).json({ error: 'Not found' });
});

export default app;