import express, { json, urlencoded } from 'express';
import cors from 'cors';
import { FinancialsRouter } from './routes/financials.route';
//import { RegisterRoutes } from './routes/routes';
///import './routes/reefapi.v0.js';

const app = express();
const financialsRouter = new FinancialsRouter();
// Middleware to parse JSON and URL-encoded data
app.use(urlencoded({ extended: true }));
app.use(json());

// Enable CORS
app.use(cors());

// Register routes generated by TSOA
//RegisterRoutes(app);

// Register routes
app.use('/api/v0', financialsRouter.getRouter());

// Handle 404 errors
app.use((req, res) => {
  res.status(404).json({ error: 'Not found' });
});

export default app;